# Generated by Django 3.1.1 on 2020-12-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_applicant_organization_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=40)),
                ('contracts', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('total_skills', models.IntegerField()),
                ('skill_value_rating', models.IntegerField()),
                ('external_app_link', models.CharField(blank=True, max_length=50, null=True)),
                ('org_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.organization_admin')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.organization')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.state')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('contracts', models.CharField(max_length=30)),
                ('matching_skills', models.IntegerField()),
                ('total_skills', models.IntegerField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.applicant')),
                ('job_listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job_listing')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.organization')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.state')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='Resumes')),
                ('citizen', models.IntegerField(verbose_name='Are you a citizen of the United States?')),
                ('authorized', models.IntegerField(verbose_name='Are you authorized to work in the US?')),
                ('felony', models.IntegerField(verbose_name='Have you been convicted of a felony?')),
                ('felony_desc', models.CharField(max_length=30, verbose_name='Description of Felony')),
                ('start_date', models.DateField(verbose_name='Date available to start working')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.applicant')),
                ('job_listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job_listing')),
                ('orgization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.organization')),
            ],
        ),
    ]
