# Generated by Django 3.1.1 on 2020-12-08 05:22

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
                ('state_abbrev', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.ethnicity')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.state')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Person',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('size', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=20)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.state')),
            ],
        ),
    ]
