# Generated by Django 3.1.1 on 2020-12-08 05:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.person')),
                ('website', models.CharField(max_length=35)),
                ('skills', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
            bases=('User.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Admin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.person')),
                ('title', models.CharField(max_length=20)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.organization')),
            ],
            options={
                'verbose_name': 'Organization Admin',
                'verbose_name_plural': 'Organization Admin',
            },
            bases=('User.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
